### PR TITLE
Thanks!

### PR DESCRIPTION
**Pull request by Gamerfiend**
Hey I noticed you branched off my work! Mind if I merge the changes into my main branch? 👍 :D

### CODE REVIEW

**Comment by Gamerfiend** [comment]
@gergondet

**Comment by gergondet** [comment]
Hi @Gamerfiend 

Sure, no problem, I meant to open a PR today actually :+1: 

Note: the credits for [`6c40036` (#3)](https://github.com/Gamerfiend/raylib-3D/pull/3/commits/6c40036d0f8ba360604c636b8053283979bc5869) goes to @FabienPean as I took the fix from #2

PS: would you mind adding a LICENSE to the repository? Thanks!

**Comment by Gamerfiend** [comment]
@gergondet I merged in the other pull request, looks like there is a conflict! And I can add a license for sure.. where do I get that? I just want to do MIT

**Comment by gergondet** [comment]
I've rebased my branch on the current master so there is no more conflict.

> And I can add a license for sure.. where do I get that? I just want to do MIT

According to [this](https://choosealicense.com/licenses/mit/) you only have to add a LICENSE file to the repository with the MIT license text. Thanks

**Pull request merged**
